### ISSUE TITLE
Could not install emacs-plus@28 --with-x11

### ISSUE THREAD

**Issue by d12frosted** [d12frosted/homebrew-emacs-plus#279]
Please make sure to follow these steps (and mark the checkboxes):

- [X] run `brew update` and try to reproduce the issue again
- [X] run `brew doctor`, fix all issues and try to reproduce your issue again
- [X] run `brew config` and `brew doctor` and include their output

## What you were trying to do

Install `emacs-plus@28` with X11.

## What happened (include command output)

<pre>
$ brew install emacs-plus@28 --with-x11
</pre>

Full output can be found in [Workflow logs](https://github.com/d12frosted/homebrew-emacs-plus/pull/277/checks?check_run_id=1464342793)

<details>
  <summary>Command output</summary>
  <pre>

DYLD_FRAMEWORK_PATH=/private/tmp/python@3.9-20201129-92346-l5pztc/Python-3.9.0 CC='clang' LDSHARED='clang -bundle -undefined dynamic_lookup -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk   ' OPT='-DNDEBUG -g -fwrapv -O3 -Wall' 	_TCLTK_INCLUDES='' _TCLTK_LIBS='' 	./python.exe -E ./setup.py  build
running build
running build_ext
Traceback (most recent call last):
  File "/private/tmp/python@3.9-20201129-92346-l5pztc/Python-3.9.0/./setup.py", line 2614, in <module>
    main()
  File "/private/tmp/python@3.9-20201129-92346-l5pztc/Python-3.9.0/./setup.py", line 2584, in main
    setup(# PyPI Metadata (PEP 301)
  File "/private/tmp/python@3.9-20201129-92346-l5pztc/Python-3.9.0/Lib/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/private/tmp/python@3.9-20201129-92346-l5pztc/Python-3.9.0/Lib/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/private/tmp/python@3.9-20201129-92346-l5pztc/Python-3.9.0/Lib/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/private/tmp/python@3.9-20201129-92346-l5pztc/Python-3.9.0/Lib/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/private/tmp/python@3.9-20201129-92346-l5pztc/Python-3.9.0/Lib/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/private/tmp/python@3.9-20201129-92346-l5pztc/Python-3.9.0/Lib/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/private/tmp/python@3.9-20201129-92346-l5pztc/Python-3.9.0/Lib/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/private/tmp/python@3.9-20201129-92346-l5pztc/Python-3.9.0/./setup.py", line 470, in build_extensions
    self.detect_modules()
  File "/private/tmp/python@3.9-20201129-92346-l5pztc/Python-3.9.0/./setup.py", line 1807, in detect_modules
    self.detect_readline_curses()
  File "/private/tmp/python@3.9-20201129-92346-l5pztc/Python-3.9.0/./setup.py", line 1038, in detect_readline_curses
    (tuple(int(n) for n in dep_target.split('.')[0:2])
AttributeError: 'int' object has no attribute 'split'
make: *** [sharedmods] Error 1
==> Kept temporary files
Temporary files retained at /private/tmp/python@3.9-20201129-92346-l5pztc
ln -s ../Cellar/python@3.9/3.9.0_1/bin/2to3 2to3
ln -s ../Cellar/python@3.9/3.9.0_1/bin/2to3-3.9 2to3-3.9
ln -s ../Cellar/python@3.9/3.9.0_1/bin/easy_install-3.9 easy_install-3.9
ln -s ../Cellar/python@3.9/3.9.0_1/bin/idle3 idle3
ln -s ../Cellar/python@3.9/3.9.0_1/bin/idle3.9 idle3.9
ln -s ../Cellar/python@3.9/3.9.0_1/bin/pip3 pip3
ln -s ../Cellar/python@3.9/3.9.0_1/bin/pip3.9 pip3.9
ln -s ../Cellar/python@3.9/3.9.0_1/bin/pydoc3 pydoc3
ln -s ../Cellar/python@3.9/3.9.0_1/bin/pydoc3.9 pydoc3.9
ln -s ../Cellar/python@3.9/3.9.0_1/bin/python3 python3
ln -s ../Cellar/python@3.9/3.9.0_1/bin/python3-config python3-config
ln -s ../Cellar/python@3.9/3.9.0_1/bin/python3.9 python3.9
ln -s ../Cellar/python@3.9/3.9.0_1/bin/python3.9-config python3.9-config
ln -s ../Cellar/python@3.9/3.9.0_1/bin/wheel3 wheel3
ln -s ../../../Cellar/python@3.9/3.9.0_1/share/man/man1/python3.1 python3.1
ln -s ../../../Cellar/python@3.9/3.9.0_1/share/man/man1/python3.9.1 python3.9.1
ln -s ../../Cellar/python@3.9/3.9.0_1/lib/pkgconfig/python-3.9-embed.pc python-3.9-embed.pc
ln -s ../../Cellar/python@3.9/3.9.0_1/lib/pkgconfig/python-3.9.pc python-3.9.pc
ln -s ../../Cellar/python@3.9/3.9.0_1/lib/pkgconfig/python3-embed.pc python3-embed.pc
ln -s ../../Cellar/python@3.9/3.9.0_1/lib/pkgconfig/python3.pc python3.pc
ln -s ../../Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Headers Headers
ln -s ../../Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Python Python
ln -s ../../Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Resources Resources
ln -s ../../../Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9 3.9
ln -s ../../../Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/Current Current

  </pre>
</details>

**Comment by jvtrigueros** [comment]
This happens even without `--with-x11`, seems to be an issue with a patch for Python@3.9 and Big Sur.

**Comment by d12frosted** [comment]
@jvtrigueros right, I need to update the logs in this issue. Current logs are really related to Python 3.9, which was recently fixed. See https://github.com/d12frosted/homebrew-emacs-plus/pull/280 for more up to date information.

**Comment by d12frosted** [comment]
See #345, it works now.
