### ISSUE TITLE
Service is not starting

### ISSUE THREAD

**Issue by SolidRhino** [d12frosted/homebrew-emacs-plus#490]
I try to start the service that is delivered with this formula. I use this command:
`brew services start d12frosted/emacs-plus/emacs-plus@28`

The following error occurs when I run that command:
```
Bootstrap failed: 5: Input/output error
Try re-running the command as root for richer errors.
Error: Failure while executing; `/bin/launchctl bootstrap gui/501 /Users/*/Library/LaunchAgents/homebrew.mxcl.emacs-plus@28.plist` exited with 5.
```

I get the following when I run the command with the -v option:
```
PATH value was changed to:
/usr/local/opt/make/libexec/gnubin
/usr/local/opt/autoconf/libexec/gnubin
/usr/local/opt/gnu-sed/libexec/gnubin
/usr/local/opt/gnu-tar/libexec/gnubin
/usr/local/opt/awk/libexec/gnubin
/usr/local/opt/coreutils/libexec/gnubin
/usr/local/opt/pkg-config/libexec/gnubin
/usr/local/opt/texinfo/libexec/gnubin
/usr/local/opt/xz/libexec/gnubin
/usr/local/Cellar/gnutls/3.7.7/libexec/gnubin
/usr/local/opt/librsvg/libexec/gnubin
/usr/local/Cellar/little-cms2/2.13.1_1/libexec/gnubin
/usr/local/opt/jansson/libexec/gnubin
/usr/local/Cellar/imagemagick/7.1.0-45/libexec/gnubin
/usr/local/opt/dbus/libexec/gnubin
/usr/local/Cellar/mailutils/3.15_1/libexec/gnubin
/usr/local/opt/make/bin
/usr/local/opt/autoconf/bin
/usr/local/opt/gnu-sed/bin
/usr/local/opt/gnu-tar/bin
/usr/local/opt/awk/bin
/usr/local/opt/coreutils/bin
/usr/local/opt/pkg-config/bin
/usr/local/opt/texinfo/bin
/usr/local/opt/xz/bin
/usr/local/opt/gnutls/bin
/usr/local/opt/librsvg/bin
/usr/local/opt/little-cms2/bin
/usr/local/opt/jansson/bin
/usr/local/opt/imagemagick/bin
/usr/local/opt/dbus/bin
/usr/local/opt/mailutils/bin
/usr/local/Homebrew/Library/Homebrew/shims/shared
/Users/*/.nix-profile/bin
/nix/var/nix/profiles/default/bin
/Users/*/.emacs.d/bin
/usr/local/opt/grep/libexec/gnubin
/Users/*/.composer/vendor/bin
/Users/*/.cargo/bin
/usr/local/sbin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/Applications/VMware Fusion.app/Contents/Public
/usr/local/share/dotnet
~/.dotnet/tools
/usr/local/MacGPG2/bin
/Library/TeX/texbin
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-autoupdate/cmd
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-command-not-found/cmd
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/cmd
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/cmd
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle/cmd
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-aliases/cmd
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd
==> which tar
/usr/local/opt/gnu-tar/libexec/gnubin/tar
==> which ls
/usr/local/opt/coreutils/libexec/gnubin/ls
==> Generated service file for emacs-plus@28:
   <?xml version="1.0" encoding="UTF-8"?>
   <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
   <plist version="1.0">
   <dict>
     <key>Label</key>
     <string>homebrew.mxcl.emacs-plus@28</string>
     <key>ProgramArguments</key>
     <array>
       <string>/usr/local/opt/emacs-plus@28/bin/emacs</string>
       <string>--fg-daemon</string>
     </array>
     <key>RunAtLoad</key>
     <true/>
     <key>StandardOutPath</key>
     <string>/tmp/homebrew.mxcl.emacs-plus.stdout.log</string>
     <key>StandardErrorPath</key>
     <string>/tmp/homebrew.mxcl.emacs-plus.stderr.log</string>
   </dict>
   </plist>


/bin/launchctl enable gui/501/homebrew.mxcl.emacs-plus@28
/bin/launchctl bootstrap gui/501 /Users/*/Library/LaunchAgents/homebrew.mxcl.emacs-plus@28.plist
Bootstrap failed: 5: Input/output error
Try re-running the command as root for richer errors.
Error: Failure while executing; `/bin/launchctl bootstrap gui/501 /Users/*/Library/LaunchAgents/homebrew.mxcl.emacs-plus@28.plist` exited with 5.
```

I get the following when I run it with the --debug option:

```
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/d12frosted/homebrew-emacs-plus/Formula/emacs-plus@28.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/make.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/autoconf.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnu-sed.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnu-tar.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/awk.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/coreutils.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/texinfo.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/xz.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gnutls.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/librsvg.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/little-cms2.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/jansson.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/imagemagick.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/dbus.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mailutils.rb
Bootstrap failed: 5: Input/output error
Try re-running the command as root for richer errors.
Error: Failure while executing; `/bin/launchctl bootstrap gui/501 /Users/*/Library/LaunchAgents/homebrew.mxcl.emacs-plus@28.plist` exited with 5.
/usr/local/Homebrew/Library/Homebrew/utils.rb:319:in `safe_system'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:239:in `launchctl_load'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:256:in `service_load'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:111:in `block in start'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:86:in `each'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/services_cli.rb:86:in `start'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service/commands/start.rb:12:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:111:in `services'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

If I run it as root, it appears to work perfectly.

Could someone please help me fix this error?

Thank you :-)

**Comment by Eirikantonsen** [comment]
I've run into the same issue, and have had no luck troubleshooting it.
On a M2 air for emacs-plus@29.

**Comment by vedkothavade** [comment]
Same issue, M1 Pro on emacs-plus@29 --with-native-comp

**Comment by BoundaryValueProblems** [comment]
Sorry for my naive question, but what this background service via `brew services start d12frosted/emacs-plus/emacs-plus@28` does? Under what circumstances would it be useful? I haven't run this background service so far, and I just simply execute emacs when I need it. Thanks!

**Comment by vedkothavade** [comment]
> Sorry for my naive question, but what this background service via `brew services start d12frosted/emacs-plus/emacs-plus@28` does? Under what circumstances would it be useful? I haven't run this background service so far, and I just simply execute emacs when I need it. Thanks!

It would allow you to use Emacs in in a client/server mode, where the server is the service and you launch new clients with `emacsclient`. This reduces startup time for new clients to basically 0, whereas launching new instances of Emacs normally can be quite slow depending on your config.

**Comment by BoundaryValueProblems** [comment]
Thanks a lot, @vedkothavade !
In my case, my emacs config is relatively simple, and I have never faced problems of slow startup of emacs. Hence, I probably don't need this background service at this point.

**Comment by paskn** [comment]
Same here. 

Ventura 13.3.1
MBP M2 2022

**Comment by paskn** [comment]
Apparently, this has been solved for me by one of the recent updates.


Ventura 13.3.1
MBP M2 2022
emacs-plus@28 
```
( system-configuration-features)
=> "ACL GIF GLIB GMP GNUTLS IMAGEMAGICK JPEG JSON LCMS2 LIBXML2 MODULES NATIVE_COMP NOTIFY KQUEUE NS PDUMPER PNG RSVG THREADS TIFF TOOLKIT_SCROLL_BARS XIM ZLIB"
```
