### ISSUE TITLE
[Q] Does this work on Linux?

### ISSUE THREAD

**Issue by NightMachinery** [d12frosted/homebrew-emacs-plus#565]

**Comment by d12frosted** [comment]
I have never tested, so can't answer this question. But I am pretty sure that not all features provided by this formula would work.

**Comment by quarkgluant** [comment]
I just tried under Fedora 38 and Ubuntu 22.04.2 LTS, the 2 installations fail with the same error
`fatal error: AppKit/AppKit.h: No such file or directory`
```shell
configure:11353: checking for AppKit/AppKit.h
2524   │ configure:11353: /home/linuxbrew/.linuxbrew/bin/gcc-12 -c -Os -w -pipe -march=native -DFD_SETSIZE=10000 -DDARWIN_UNLIMITED_SELECT -x objective-c    -I/home/linuxbrew/.linuxbrew/opt/berkeley-db@5/include
       │  -isystem/home/linuxbrew/.linuxbrew/include -F/home/linuxbrew/.linuxbrew/Frameworks -x objective-c  conftest.c >&5
2525   │ conftest.c:104:10: fatal error: AppKit/AppKit.h: No such file or directory
2526   │   104 | #include <AppKit/AppKit.h>
2527   │       |          ^~~~~~~~~~~~~~~~~
2528   │ compilation terminated.
2529   │ configure:11353: $? = 1
2530   │ configure: failed program was:
2531   │ | /* confdefs.h */
```

**Comment by d12frosted** [comment]
@quarkgluant you can try building without cocoa (e.g. `--without-cocoa`) and optionally `--with-x`. By default Emacs+ is built with cocoa support which is not available on non-macOS systems :)

**Comment by quarkgluant** [comment]
```
❯ brew install emacs-plus --without-cocoa
Error: unknown keyword: tap
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:186:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/d12frosted/homebrew-emacs-plus/Formula/emacs-plus@28.rb:103:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:401:in `new'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:401:in `get_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:671:in `factory'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/parser.rb:645:in `block in formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/parser.rb:641:in `map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/parser.rb:641:in `formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/parser.rb:317:in `parse'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:169:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```

**Comment by d12frosted** [comment]
See #567

**Comment by quarkgluant** [comment]
EDIT: thanks @d12frosted , it works on both Ubuntu and Fedora
