### ISSUE TITLE
Installation fails with recent brew update

### ISSUE THREAD

**Issue by mariusk** [d12frosted/homebrew-emacs-plus#629]
I've had no issues until recently. Today after upgrading all my brew packages, when I try to install emacs-plus, I get:

```
~ brew install emacs-plus
Error: wrong number of arguments (given 4, expected 3)
Please report this issue:
  https://docs.brew.sh/Troubleshooting
Warning: Removed Sorbet lines from backtrace!
Rerun with --verbose to see the original backtrace
/opt/homebrew/Library/Homebrew/formula.rb:204:in `initialize'
/opt/homebrew/Library/Taps/d12frosted/homebrew-emacs-plus/Formula/emacs-plus@29.rb:98:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:494:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:494:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:734:in `factory'
/opt/homebrew/Library/Homebrew/cli/parser.rb:655:in `block in formulae'
/opt/homebrew/Library/Homebrew/cli/parser.rb:651:in `map'
/opt/homebrew/Library/Homebrew/cli/parser.rb:651:in `formulae'
/opt/homebrew/Library/Homebrew/cli/parser.rb:323:in `parse'
/opt/homebrew/Library/Homebrew/cmd/install.rb:167:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

**Comment by anthonyclarka2** [comment]
Same error here, when running `brew info emacs-plus@30 --verbose` or `brew install emacs-plus@30 --verbose`

```
brew install emacs-plus@30 --verbose
==> Downloading https://formulae.brew.sh/api/formula.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Error: wrong number of arguments (given 4, expected 3)
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/formula.rb:204:in `initialize'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
/opt/homebrew/Library/Taps/d12frosted/homebrew-emacs-plus/Formula/emacs-plus@30.rb:99:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:494:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:494:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:734:in `factory'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cli/parser.rb:655:in `block in formulae'
/opt/homebrew/Library/Homebrew/cli/parser.rb:651:in `map'
/opt/homebrew/Library/Homebrew/cli/parser.rb:651:in `formulae'
/opt/homebrew/Library/Homebrew/cli/parser.rb:323:in `parse'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:89:in `block in create_validator_slow'
/opt/homebrew/Library/Homebrew/cmd/install.rb:167:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

brew config:
```
brew config
HOMEBREW_VERSION: 4.1.22-55-gd68e3e5
ORIGIN: https://github.com/Homebrew/brew
HEAD: d68e3e563ef76b96b75df2e54686a94fec5c4474
Last commit: 10 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 71b8e841935b133b7c9855528dc714446487032d
Core tap last commit: 37 minutes ago
Core tap branch: master
Core tap JSON: 30 Nov 23:56 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BAT_THEME: TwoDark
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.43.0 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 14.1.2-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: 15.0.1
Rosetta 2: false
```

**Comment by emmamm05** [comment]
This might work as a temp fix
`brew edit emacs-plus@29`

```diff
diff --git a/Formula/emacs-plus@29.rb b/Formula/emacs-plus@29.rb 
index ca2cb58..00f5e45 100644                                    
--- a/Formula/emacs-plus@29.rb                                   
+++ b/Formula/emacs-plus@29.rb                                   
@@ -94,7 +94,7 @@ class EmacsPlusAT29 < EmacsBase                
   #                                                             
   # Initialize                                                  
   #                                                             
-  def initialize(*args, &block)                                 
+  def initialize(*args, **kwargs, &block)                       
     a = super                                                   
     expand_path                                                 
     a                                                           
```

**Comment by d12frosted** [comment]
@emmamm05 sounds about right; would apreciate a PR 🙏

**Comment by anthonyclarka2** [comment]
@emmamm05 just FYI I've created a PR for this issue, I hope this isn't stepping on your toes, please let me know if I've acted too hastily.

**Comment by emmamm05** [comment]
No worries, go ahead!. I tested it with version 29 on my end, and that was enough to get it running. It looks like in Ventura brew is using Ruby 3.0+ which introduced changes in kwargs.

**Comment by d12frosted** [comment]
The fix is in master now. Thanks @emmamm05 and @anthonyclarka2 (@aclarknexient ) for the quick fix ❤️
