### ISSUE TITLE
--with-xwidgets seems to be broken

### ISSUE THREAD

**Issue by agzam** [d12frosted/homebrew-emacs-plus#94]
```
18:27:28 ~/.emacs.d [develop]$ brew install emacs-plus --with-xwidgets --HEAD
==> Installing emacs-plus from d12frosted/emacs-plus
==> Installing dependencies for d12frosted/emacs-plus/emacs-plus: gnu-sed, texinfo, graphite2, harfbuzz, imagemagick@6
==> Installing d12frosted/emacs-plus/emacs-plus dependency: gnu-sed
==> Downloading https://homebrew.bintray.com/bottles/gnu-sed-4.5.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring gnu-sed-4.5.high_sierra.bottle.tar.gz
==> Caveats
The command has been installed with the prefix "g".
If you do not want the prefix, install using the "with-default-names" option.

If you need to use these commands with their normal names, you
can add a "gnubin" directory to your PATH from your bashrc like:
  PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"

Additionally, you can access their man pages with normal names if you add
the "gnuman" directory to your MANPATH from your bashrc as well:
  MANPATH="/usr/local/opt/gnu-sed/libexec/gnuman:$MANPATH"
==> Summary
🍺  /usr/local/Cellar/gnu-sed/4.5: 12 files, 529KB
==> Installing d12frosted/emacs-plus/emacs-plus dependency: texinfo
==> Downloading https://homebrew.bintray.com/bottles/texinfo-6.5.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring texinfo-6.5.high_sierra.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because software that uses TeX, such as lilypond and octave, require a newer
version of these files.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/texinfo/bin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/texinfo/lib

==> Summary
🍺  /usr/local/Cellar/texinfo/6.5: 408 files, 8.3MB
==> Installing d12frosted/emacs-plus/emacs-plus dependency: graphite2
==> Downloading https://homebrew.bintray.com/bottles/graphite2-1.3.12.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring graphite2-1.3.12.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/graphite2/1.3.12: 18 files, 235.9KB
==> Installing d12frosted/emacs-plus/emacs-plus dependency: harfbuzz
==> Downloading https://homebrew.bintray.com/bottles/harfbuzz-1.8.8.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring harfbuzz-1.8.8.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/harfbuzz/1.8.8: 151 files, 6.3MB
==> Installing d12frosted/emacs-plus/emacs-plus dependency: imagemagick@6
==> Downloading https://homebrew.bintray.com/bottles/imagemagick@6-6.9.10-10.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring imagemagick@6-6.9.10-10.high_sierra.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/imagemagick@6/bin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/imagemagick@6/lib
    CPPFLAGS: -I/usr/local/opt/imagemagick@6/include
For pkg-config to find this software you may need to set:
    PKG_CONFIG_PATH: /usr/local/opt/imagemagick@6/lib/pkgconfig

==> Summary
🍺  /usr/local/Cellar/imagemagick@6/6.9.10-10: 1,471 files, 23MB
==> Installing d12frosted/emacs-plus/emacs-plus --HEAD --with-xwidgets
==> Cloning https://github.com/emacs-mirror/emacs.git
Cloning into '/Users/mayvenn/Library/Caches/Homebrew/emacs-plus--git'...
remote: Counting objects: 4062, done.
remote: Compressing objects: 100% (3825/3825), done.
remote: Total 4062 (delta 304), reused 1073 (delta 140), pack-reused 0
Receiving objects: 100% (4062/4062), 39.62 MiB | 6.38 MiB/s, done.
Resolving deltas: 100% (304/304), done.
Checking out files: 100% (3892/3892), done.
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
==> Downloading https://gist.githubusercontent.com/aatxe/260261daf70865fbf1749095de9172c5/raw/214b50c62450be1cbee9f11cecba846dd66c7d06/patch-m
######################################################################## 100.0%
==> Downloading https://gist.githubusercontent.com/fuxialexander/0231e994fd27be6dd87db60339238813/raw/b30c2d3294835f41e2c8afa1e63571531a38f3cf
######################################################################## 100.0%
==> Patching
==> Applying patch-multicolor-font.diff
patching file src/macfont.m
Hunk #1 succeeded at 2345 (offset -28 lines).
==> Applying 0_all_webkit.patch
patching file configure.ac
Hunk #2 succeeded at 2710 (offset -31 lines).
patching file lisp/xwidget.el
patching file nextstep/templates/Info.plist.in
patching file src/Makefile.in
Hunk #1 succeeded at 417 (offset 3 lines).
patching file src/emacs.c
Hunk #1 succeeded at 1577 (offset 36 lines).
Hunk #2 succeeded at 1653 (offset 36 lines).
patching file src/nsterm.m
patching file src/nsxwidget.h
patching file src/nsxwidget.m
patching file src/xwidget.c
Hunk #25 FAILED at 990.
Hunk #31 succeeded at 1444 with fuzz 1.
1 out of 31 hunks FAILED -- saving rejects to file src/xwidget.c.rej
patching file src/xwidget.h
patch unexpectedly ends in middle of line
Error: Failure while executing; `patch -g 0 -f -p1 -i /private/tmp/emacs-plus--patch-20180819-43261-sswep/0_all_webkit.patch` exited with 1.
```

**Comment by d12frosted** [comment]
It's interesting. Works for me with the latest `master`. @agzam can you please try again? 😸

**Comment by agzam** [comment]
nope... still broken for me
```
HEAD is now at 4ee34ee82d * lisp/progmodes/idlw-shell.el: Use lexical-binding
==> Downloading https://gist.githubusercontent.com/aatxe/260261daf70865fbf1749095de9172c5/raw/214b50c62450be1cbee9f11cecba846dd66c7d06/patch-multicolor-font.diff
######################################################################## 100.0%
==> Downloading https://gist.githubusercontent.com/fuxialexander/0231e994fd27be6dd87db60339238813/raw/b30c2d3294835f41e2c8afa1e63571531a38f3cf/0_all_webkit.patch
######################################################################## 100.0%
==> Patching
==> Applying patch-multicolor-font.diff
patching file src/macfont.m
Hunk #1 succeeded at 2345 (offset -28 lines).
==> Applying 0_all_webkit.patch
patching file configure.ac
Hunk #2 succeeded at 2712 (offset -29 lines).
Hunk #3 succeeded at 5499 (offset 4 lines).
patching file lisp/xwidget.el
patching file nextstep/templates/Info.plist.in
patching file src/Makefile.in
Hunk #1 succeeded at 417 (offset 3 lines).
patching file src/emacs.c
Hunk #1 succeeded at 1545 (offset 4 lines).
Hunk #2 succeeded at 1621 (offset 4 lines).
patching file src/nsterm.m
patching file src/nsxwidget.h
patching file src/nsxwidget.m
patching file src/xwidget.c
Hunk #25 FAILED at 990.
Hunk #31 succeeded at 1444 with fuzz 1.
1 out of 31 hunks FAILED -- saving rejects to file src/xwidget.c.rej
patching file src/xwidget.h
patch unexpectedly ends in middle of line
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `write': Broken pipe (Errno::EPIPE)
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `puts'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `rescue in block (3 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:31:in `block (3 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:30:in `fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:30:in `block (2 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:27:in `open'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:27:in `block in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:26:in `safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:719:in `build'
	from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:311:in `install'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:321:in `install_formula'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:253:in `block in install'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:251:in `each'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:251:in `install'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: undefined method `shelljoin' for nil:NilClass
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:546:in `initialize'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:7:in `new'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:7:in `rewrite_child_error'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:78:in `block (3 levels) in safe_fork'
/usr/local/Homebrew/Library/Homebrew/utils.rb:399:in `ignore_interrupts'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:57:in `block (2 levels) in safe_fork'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:27:in `open'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:27:in `block in safe_fork'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:26:in `safe_fork'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:719:in `build'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:311:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:321:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:253:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:251:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:251:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

**Comment by vv111y** [comment]
I just had this problem as well

**Comment by d12frosted** [comment]
Got it. Will play around with the patch tomorrow.

Thanks for checking :)

**Comment by d12frosted** [comment]
I bring the news. First of all, I didn't get the error because of a typo (so the patch was not used in the first place). Secondly, I've tried to fix the patch, but since conflicts are not trivial, I've asked more competent people to check it. Will keep you updated.

**Comment by d12frosted** [comment]
By the way, right now you can still install it by calling `brew` with `--debug` option and then switching to some old commit (1 month?).

```
$ brew install --debug emacs-plus --HEAD --with-xwidgets
```

**Comment by agzam** [comment]
--with-pdumper option doesn't seem to be working either ;(

**Comment by d12frosted** [comment]
Still no news with `xwidgets` option. But there is a PR for `pdumper`: https://github.com/d12frosted/homebrew-emacs-plus/pull/97. Will be merged soon.

Sorry for making you to wait for so long.

**Comment by jsmestad** [comment]
@d12frosted I couldnt dig up anything on xwidgets yet, have you heard anything (2019 update)?

**Comment by d12frosted** [comment]
@jsmestad unfortunately no :(

**Comment by pcr910303** [comment]
Have a new patch for 2019 :-)

I'm not an emacs expert; actually I first saw the emacs C sources today.
However, I made a patch (based on [the fork](https://github.com/veshboo/emacs) and [the original patch](https://gist.github.com/fuxialexander/0231e994fd27be6dd87db60339238813/)) [here](https://gist.github.com/pcr910303/fd4811f13463cfa0170626418cbc8f6a).

It's based on [d2d4916046e31e46598f0a0edbc65e75b8cb4cc3](https://emba.gnu.org/emacs/emacs/tree/d2d4916046e31e46598f0a0edbc65e75b8cb4cc3).

I'm still testing, (it's been about 4 hours since I made this patch), but it looks like all of it's features are well working (like scrolling with functions, resizing, etc...).

**Comment by d12frosted** [comment]
@pcr910303 would be so cool of you to send me a PR that I can merge :smile_cat:

**Comment by shuxiao9058** [comment]
why not support Mojave?

**Comment by d12frosted** [comment]
Actually, I don't remember. I've removed this restriction locally and will push it once I am in the office.

**Comment by d12frosted** [comment]
@shuxiao9058 pushed the change, have fun!

**Comment by shuxiao9058** [comment]
> @shuxiao9058 pushed the change, have fun!

I will try later.

**Comment by d12frosted** [comment]
`--HEAD` builds for me, but --with-xwidgets` doesn't. Error during `make` stage.

**Comment by pcr910303** [comment]
@d12frosted Does HEAD build? For me it doesn’t, because of some obscure `makeinfo` command(a few hours ago).
I’ll check if that’s because of my patch.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by d12frosted** [comment]
@pcr910303 as I said, plain `--HEAD` builds. But when I add `--with-xwidgets`, it doesn't :(

**Comment by pcr910303** [comment]
@d12frosted Okay, I was wondering why my local clone was building while the brew formula wasn't :-(

Apparently I didn't add all files into the staging area and performed a `git diff` (ah... stubborn me :-()
I'll open another PR for that, sorry for my repeated mistakes.

**Comment by d12frosted** [comment]
@pcr910303 no problem :) waiting for PR

**Comment by pcr910303** [comment]
@d12frosted Actually I already made my PR about 15mins ago 👍

**Comment by d12frosted** [comment]
@pcr910303 lol, let me check it then

**Comment by d12frosted** [comment]
Ok, builds with latest PR. :100:

**Comment by d12frosted** [comment]
And works. Managed to run it! Yay. @agzam you should be happy!

**Comment by agzam** [comment]
I can't wait to try this out. Damn it takes too long to compile Emacs. I get anxiety panic when I have to be with no Emacs, even for a few minutes.

**Comment by d12frosted** [comment]
> Damn it takes too long to compile Emacs. I get anxiety panic when I have to be with no Emacs, even for a few minutes.

Oh, I know the feeling! I totally understand it!
